### ISSUE TITLE
Zip archive to include submodule

### ISSUE THREAD

**Issue by am11** [dear-github/dear-github#214]
When possible (accessibility-wise), would be nice if submodules are packed in the zip archive of branch.

For example:

```powershell
# in Windows PowerShell
cd /temp
wget https://github.com/Snaipe/Criterion/archive/bleeding.zip -OutFile criterion-bleeding.zip
Expand-Archive criterion-bleeding.zip -DestinationPath .

# now compare
ls -r criterion-bleeding/dependencies
# with
cat criterion-bleeding/.gitmodules
```

tells us Criterion has three submodules listed in `.gitmodules` file which were not included in the zip archive.

**Comment by rschuetzler** [comment]
Including submodules in releases would also be nice.

**Comment by maddanio** [comment]
Any chance? :)

**Comment by obskyr** [comment]
Big +1 from me! Submodules are cumbersome as it is, but the fact that they're not included in the zip makes it impossible to use submodules in a project you want to distribute via unadorned source downloads on GitHub.

**Comment by sebres** [comment]
Alleged answer of the github about the subject (posted in https://blogs.harvard.edu/acts/2012/10/18/github-zip-doesnt-include-submodules/#comment-975):
> Currently zip/tarballs are generated using git-archive, which does not include submodules. If the git team adds that functionality to git-archive, we’ll be sure to update it so we can include submodules as well.

Looking at the [git-documentation](https://git-scm.com/docs/git-archive) does not show me something about support of submodules...

The issue is also related to: the referenced modules are revisions-pinned (different branches could have different submodules and/or could address different commits within); they could be recursive (have submodules too), etc.

**Comment by gergelytakacs** [comment]
Has this been solved? It would be awesome to have the submodules in the ZIP downloads and releases:(

**Comment by maddanio** [comment]
This is probably something for upstream, I.e. git. About pinning etc, simples would be to effectively do git submodule update —init —recursive, which is the first thing I do in any of my repos

**Comment by gergelytakacs** [comment]
Sure, but many people come to GIT just for the software, and dont know what
git is. The 'Download ZIP' button, therefore defeats its purpose.

Anyways, this is truly for Git to solve.

**Comment by tadeu** [comment]
There is a third-party alternative that will archive all submodules together: https://github.com/Kentzo/git-archive-all

**Comment by syedmohsinbukhari** [comment]
This would be super cool

**Comment by guenthereder** [comment]
It would be very nice to have an "per-project"-option to enable including the submodules in the zip-download.

**Comment by phillipjohnston** [comment]
Not only is this "nice to have", it's actually quite a support nightmare for me on all of my projects with submodules. I get regular complaints, no matter how many times I post DO NOT USE THE GITHUB SOURCE ZIP FILES.

**Comment by norlesh** [comment]
Requiring end users of the repositories to learn the intricacies of git and rebuild the project structure in order to casually test a project because Github couldn't be chuffed customizing some code instead of just wrapping git-archive is BAULKED

**Comment by TheTechRobo** [comment]
The only reason I'm not using submodules right now is this. I use Python and the only damn reason I include .mo files in my source code is so you can download and run, no compilation necessary.

**Comment by crocket** [comment]
To be honest, git submodules are one of the worst nightmares for linux distribution package maintainers.
People should use plain old libraries instead of git submodules.

**Comment by ZLima12** [comment]
> To be honest, git submodules are one of the worst nightmares for linux distribution package maintainers.
> People should use plain old libraries instead of git submodules.

Though I myself am on this page because of a package I'm maintaining, submodules can still be useful. Especially on non-Linux systems, where the library system is abysmal. But even on Linux, for header-only libraries or similar things, submodules are fine.

Anyway, having source archives include submodules is logical. Anyone who wants the source code to a project should have all the necessary pieces to build it. If there are concerns as to file sizes, there could be radio buttons to choose whether to recursively include submodules. These buttons could simply add or remove an option in the URL to the archive. This would be enough for package maintainers, as they could use the URL for recursive submodule cloning.

**Comment by braindigitalis** [comment]
I get the feeling this isnt ever going to be fixed. It's been asked for so many times over a span of years: https://github.community/t/create-release-that-contains-submodule/1329

**Comment by pde-bakk** [comment]
Please add this, it is such a pain to have to ask end-users who don't know what git is to not use the "Download as ZIP" button.

**Comment by w3lld0ne** [comment]
upvoting this as well. very unlogical behaviour currently...

**Comment by Tumas2** [comment]
Same, this would help IMMENSLY in so many of my work projects

**Comment by yawaramin** [comment]
Hey folks, there's no need for 'me too' comments. They just spam everyone who's subscribed for real updates, and I would be surprised if individual comments would be given more importance than high numbers of upvotes, https://github.com/dear-github/dear-github/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

If you want to push for an issue, upvote it.

**Comment by tenbits** [comment]
That's why we still keep zip-ing the source code and including it to git. _21st century_

**Comment by crocket** [comment]
I think people should contribute to projects like gitea instead of begging microsoft for a functionality.
Big tech doesn't listen to people. It's also a good idea to move your repositories out of github.

**Comment by mrl5** [comment]
in case someone is looking for a workaround:
for me github action that creates draft release with customr artifact works like charm: https://github.com/mrl5/vulner/blob/d67baade397c650fde6edb7e183e9fa638b40a06/.github/workflows/draft-release.yaml
```
# https://github.com/actions/create-release
# https://github.com/actions/upload-release-asset
name: draft-release

on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get custom tarball name
        id: get_tarball_name
        run: echo ::set-output name=TARBALL_NAME::vulner-${{ github.ref_name }}

      - name: Get archived folder name for custom tarball
        id: get_archived_folder_name
        run: echo ::set-output name=ARCHIVED_FOLDER::${{ github.repository_owner }}-vulner-$(git rev-parse --short HEAD)

      - name: Create custom tarball artifact
        run: |
          mkdir -p artifacts
          tar czhvf \
            artifacts/${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz \
            --exclude="*metarepo-cpe-tag*" \
            --directory=../ \
            vulner/crates/ vulner/Cargo.lock vulner/Cargo.toml vulner/Makefile vulner/scripts/ vulner/README.md vulner/LICENSE \
            --transform s/vulner/${{ steps.get_archived_folder_name.outputs.ARCHIVED_FOLDER }}/
      - name: Build from custom tarball artifact
        run: |
          mkdir -p build
          tar xzvf artifacts/${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz \
            --directory=build
          cd build/${{ steps.get_archived_folder_name.outputs.ARCHIVED_FOLDER }}
          make build
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            DRAFT
          draft: true
          prerelease: true

      - name: Upload TAR.GZ release asset
        id: upload-tar-gz-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz
          asset_name: ${{ steps.get_tarball_name.outputs.TARBALL_NAME }}.tar.gz
          asset_content_type: application/gzip
```

**Comment by ahalekelly** [comment]
Here's my Github Action to do this:

https://github.com/ahalekelly/Dettlaff/blob/master/.github/workflows/nightly-release.yaml

```
name: nightly-release

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-nightly.zip ${{ github.event.repository.name }} -r
          
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          files: ${{ github.event.repository.name }}-nightly.zip
```
